In [311]:
import numpy as np
X_DIMENSION = 11
Y_DIMENSION = 7
T = 100

In [312]:
input = """p=0,4 v=3,-3
p=6,3 v=-1,-3
p=10,3 v=-1,2
p=2,0 v=2,-1
p=0,0 v=1,3
p=3,0 v=-2,-2
p=7,6 v=-1,-3
p=3,0 v=-1,-2
p=9,3 v=2,3
p=7,3 v=-1,2
p=2,4 v=2,-3
p=9,5 v=-3,-3"""

In [313]:
from numpy import zeros


total_map = zeros((X_DIMENSION, Y_DIMENSION))
print(total_map.shape)

(11, 7)


In [314]:
def parse_position_velocity(input):
    parsed_data = []
    
    lines = input.split('\n')
    
    for line in lines:
        if not line.strip():
            continue
        
        p_part, v_part = line.split(' v=')
        
        pos_x, pos_y = map(int, p_part.replace('p=', '').split(','))
        initial_position = np.array([pos_x, pos_y])
        
        vel_x, vel_y = map(int, v_part.split(','))
        velocity = np.array([vel_x, vel_y])
        
        parsed_data.append([initial_position, velocity])
    
    return np.array(parsed_data, dtype=object)

robot_data = parse_position_velocity(input)

initial_map = zeros((X_DIMENSION, Y_DIMENSION))
for robot_initial_position, _ in robot_data:
    initial_map[robot_initial_position[0]][robot_initial_position[1]] += 1
print("Initial map:")
print(initial_map.transpose())
print("\n")

for robot_initial_position, robot_velocity in robot_data:
    resulting_x_position = (robot_initial_position[0] + robot_velocity[0] * T) % X_DIMENSION
    resulting_y_position = (robot_initial_position[1] + robot_velocity[1] * T) % Y_DIMENSION
    total_map[resulting_x_position][resulting_y_position] += 1
resulting_map_transposed = total_map.transpose()
print(f"Map after {T} seconds:")
print(resulting_map_transposed)

y_dimension_center = int(np.ceil(Y_DIMENSION/2))
x_dimension_center = int(np.ceil(X_DIMENSION/2))
print(y_dimension_center)
print(x_dimension_center)
quadrant_1 = resulting_map_transposed[:y_dimension_center-1, x_dimension_center:X_DIMENSION]
quadrant_2 = resulting_map_transposed[:y_dimension_center-1, :x_dimension_center-1]
quadrant_3 = resulting_map_transposed[y_dimension_center:Y_DIMENSION, :x_dimension_center-1]
quadrant_4 = resulting_map_transposed[y_dimension_center:Y_DIMENSION, x_dimension_center:X_DIMENSION]




Initial map:
[[1. 0. 1. 2. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 1. 0. 1. 1.]
 [1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]]


Map after 100 seconds:
[[0. 0. 0. 0. 0. 0. 2. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 2. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0.]]
4
6
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 2.]
 [0. 1. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]]
